Settings:
  project_name: TED-DPLM
  outdir: output
  tags:
  - AR
  - ModelSize0_100-200M
  - Weighting1_1
Model:
  supports_gradient_checkpointing: false
  kwargs:
    class_name: models.GPTwDomainConditioning_esmfa.GPTwDomainConditioning_esmfa
    gpt_type: gpt2-amino_acid
    esm_type: facebook/esm2_t12_35M_UR50D
    criterion_kwargs:
      class_name: utils.objectives.DomainReweightedCriterion
      domain_weight: 1.0
      non_domain_weight: 1.0
  Optimizer_kwargs:
    class_name: torch.optim.AdamW
    lr: 0.0001
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.98
  Scheduler_kwargs:
    class_name: transformers.get_cosine_schedule_with_warmup
    num_warmup_steps: 1000
    num_training_steps: 1000000
Datamodule:
  kwargs:
    class_name: dataloader.datamodules.domainsplit_datamodule.DomainSplitDataModule
    train_split_path: ${DATA_DIR}/AFDB/splits/train_repid-entryid.tsv
    val_split_path: ${DATA_DIR}/AFDB/splits/valid_repid-entryid.tsv
    test_split_path: ${DATA_DIR}/AFDB/splits/test_repid-entryid_1k.tsv
    seq_lmdb_path: ${DATA_DIR}/AFDB/LMDB_seqonly
    domain_lmdb_path: ${DATA_DIR}/AFDB/LMDB_uid2domain_info
    cluster_lmdb_path: ${DATA_DIR}/AFDB/LMDB_train_cluster
    num_workers_per_gpu: 8
    per_gpu_batchsize: 64
    eval_batch_size: 64
    max_aa_seq_len: 1024
    shuffle_domain: true
Trainer:
  seed: 123
  max_steps: 50000
  max_epochs: -1
  accumulate_grad_batches: 1
  val_every_n_steps: 200
  log_every_n_steps: 10
  save_every_n_steps: 5000
  val_before_train: true
  watch_t1_t2_loss: false
  cal_constant_loss: false
  trackers:
  - wandb
  - tensorboard
  kwargs:
    class_name: experiments.experiments.D2S.D2S
